development:
  adapter: mysql2
  encoding: utf8
  database: loans_dev
  pool: 5
  username: 'root'
  password: '123456'
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: loans_dev
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database: loans_pro
  pool: 5
  username: root
  password: 123456
